version: "3"

services:
  app:
    build: .
    command: uvicorn financial.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///financial_data.db
    volumes:
      - ./financial_data.db:/app/financial_data.db
