FROM python:3.10

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN pip install --upgrade pip && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root

COPY get_raw_data.py .
ENV env_file .env

CMD [ "python", "./get_raw_data.py" ]
